version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running pre-build commands..."
      - mvn clean install

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -f src/main/docker/Dockerfile -t t-and-t-2 .

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push t-and-t-2
      - aws elasticbeanstalk create-application-version --application-name t-and-t-2 --version-label 0.0.2 --source-bundle file://target/spring-boot.jar
      - aws elasticbeanstalk update-environment --application-name t-and-t-2 --environment-name T-and-t-2-env --version-label <version_label>

artifacts:
  files:
    - target/*.jar