version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17
  pre_build:
    commands:
      - mvn clean
  post_build:
    commands:
      - mvn package
artifacts:
  files: target/*.jar
