
###
GET {{apiUrl}}/api/chats/247/messages/read
    ?size=5
    &page=0
    &sort=creationDate,desc
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/chats/247/messages/unread?
    size=5&
    page=0
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/chats/77/messages/read?size=20&page=0&sort=creationDate,asc
Authorization: Bearer {{token}}





###
GET {{apiUrl}}/api/chats/1/unread-messages?
    size=10&
    page=0
Authorization: Bearer {{token}}

###
PATCH {{apiUrl}}/api/chats/244/messages/last-read
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lastReadMessageId":183
}

> {% client.test("is 204", () => client.assert(response.status === 204, "status is not 204")) %}

###
PATCH {{apiUrl}}/api/chats/1/messages/last-read
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lastReadMessageId":183
}

> {% client.test("is 400", () => client.assert(response.status === 400, "status is not 400")) %}


###
GET {{apiUrl}}/api/chats/Aruba/main
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/v2/user/private-chats
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/v2/user/chats
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/api/chats
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/v2/main-countries-chats?sort=id,asc
Authorization: Bearer {{token}}

###
POST {{apiUrl}}/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"chat name",
  "description": "chat description",
  "countryId": "Aruba"
}


###
POST {{apiUrl}}/api/chats/private
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "companionId": 9
}

###
GET {{apiUrl}}/api/v2/user/public-chats
Authorization: Bearer {{token}}