

###
GET http://localhost:8080/api/chats/1/read-messages?
    lastReadMessageId=4&
    size=10&
    page=0
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/api/chats/1/unread-messages?
    lastReadMessageId=4&
    size=10&
    page=0
Authorization: Bearer {{token}}


###
PATCH http://localhost:8080/api/chats/243/messages/last-read
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lastReadMessageId": 9
}

> {% client.test("is 204", () => client.assert(response.status === 204, "status is not 204")) %}

###
GET {{apiUrl}}/api/chats/Aruba/main
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/api/v2/user/private-chats
Authorization: Bearer {{token}}


###
POST {{apiUrl}}/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"chat name",
  "description": "chat description",
  "countryId": "Aruba"
}


###
POST {{apiUrl}}/api/chats/private
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "companionId": 8
}