
###
POST {{apiUrl}}/api/authentication/login
Content-Type: application/json

{
  "password": "{{userPassword}}",
  "userEmail": "{{userEmail}}"
}

> {% client.global.set("token", response.body.token) %}


###
POST {{apiUrl}}/api/authentication/register
Content-Type: application/json

{
  "userName": "{{username}}",
  "password": "{{userPassword}}",
  "userEmail": "{{userEmail}}"
}

###
POST {{apiUrl}}/api/authentication/login
Content-Type: application/json

{
  "password": "V66M:c6%wQkK6]u",
  "userEmail": "testing@i.ua"
}

> {% client.global.set("token", response.body.token) %}

