
###
GET {{apiUrl}}/api/v2/user/private-chats
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/api/v2/user/public-chats
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/health


###
POST {{apiUrl}}/api/v2/authentication/social/register
Content-Type: application/json

{
  "userName" : "Social of Alise2",
  "userEmail" : "social2@i.ua"
}

###
POST {{apiUrl}}/api/v2/authentication/social/login
Content-Type: application/json

{
  "userEmail" : "social2@i.ua"
}