###
PUT {{apiUrl}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userName" : "new alisa name",
  "userEmail" : "234234234@i.ua",
  "about" : "123"
}


###
GET {{apiUrl}}/api/v2/users
Authorization: Bearer {{token}}