@startuml
actor Frontend
participant Backend
participant OnlineService
participant Redis
== Fetching User Statuses ==

    Frontend -> Backend : send HTTP request api/v2/users/online


alt Request for getAllUsersOnlineStatuses()
  Backend -> OnlineService : Fetch All user statuses
  OnlineService -> Redis : get values by keys user:{userId}:online
  OnlineService -> Redis : get values by keys user:{userId}:lastSeenOn
  OnlineService -> Backend : Return Map<Long, OnlineStatusDto>
  note right
  record OnlineStatusDto {
      Long userId
      Boolean isOnline;
      LocalDateTime lastSeenOn;
      }
  end note
  Backend -> Frontend : Return Map<Long, OnlineStatusDto>
end

@enduml