@startuml

skinparam linetype ortho

class OnlineStatusDto {
  - userId: Long
  - isOnline: Boolean
  - lastSeenOn: LocalDateTime
}

note right of OnlineStatusDto::lastSeenOn
 Represents the user's
 last activity timestamp
end note

@enduml
