@startuml

!theme plain
left to right direction
skinparam linetype ortho

class User {
  - about: String
  - userName: String
  - tokens: List<Token>
  - countries: List<Country>
  - chats: List<Chat>
  - password: String
  - avatar: Avatar
  - id: Long
  - userEmail: String
  - role: Role
}

class UserCountry {
  - userId: Long
  - countryId: Long
}

class UserChat {
  - userId: Long
  - chatId: Long
  - lastReadMessageId: Long
}

class Country {
  - name: String
  - flagCode: String
  - id: Long
  - chats: List<Chat>
}

class Chat {
  - id: Long
  - name: String
  - creationDate: LocalDateTime
  - messages: List<Message>
  - events: List<Event>
  - description: String
}

class Message {
  - creationDate: LocalDateTime
  - userId: Long
  - content: String
  - id: Long
  - chatId: Long
  - repliedMessageId: Long
}

class Event {
  - id: Long
  - userId: Long
  - chatId: Long
  - eventType: EventType
  - eventTime: LocalDateTime
}

enum EventType {
  JOIN,
  LEAVE,
  TYPING,
  STOPPED_TYPING
}

User -[#595959,plain]-> Country
User -[#595959,plain]-> Chat
Message -[#595959,plain]-> User
Event -[#595959,plain]-> User
Chat -[#595959,plain]-> Message
Chat -[#595959,plain]-> Event
Country -[#595959,plain]-> Chat

UserCountry  "1" *-[#595959,plain]-> "user\n1" User
UserCountry  "1" *-[#595959,plain]-> "country\n1" Country

UserChat     "1" *-[#595959,plain]-> "user\n1" User
UserChat     "1" *-[#595959,plain]-> "chat\n1" Chat

Event -[#595959,plain]-> EventType

@enduml
