name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: test

    steps:
      - name: Stop running application
        run: sudo systemctl stop talk_and_travel

      - name: Fetch updated code
        working-directory: /home/admin/talk-and-travel
        run: |
          sudo git restore .
          sudo git pull
          sudo chmod +x ./mvnw

      - name: Start service
        run: sudo systemctl start talk_and_travel
