name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Docker version
        run: docker --version

      - name: Install dependencies and test with Maven
        run: mvn clean test

      - name: Wait for Redis to be ready
        run: |
          while ! nc -z localhost 6379; do
            echo "Waiting for Redis..."
            sleep 1
          done
