name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Docker
        run: sudo apt-get install docker.io

      - name: Start Docker service
        run: sudo service docker start

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Install dependencies and test with Maven
        run: mvn clean test

      - name: Stop Docker Compose
        run: docker-compose down