on:
  push:
    branches:
      - main
      - KAN-26-setup-CI-CD

jobs:
  redeploy:
    runs-on: test
    steps:
      - name: stop running application
        run: sudo systemctl stop talk_and_travel
      - name: fetch updated code
        run: cd /home/admin/talk-and-travel && sudo git pull
      - name: run service
        run: sudo systemctl start talk_and_travel