on:
  push:
    branches:
      - main
      - KAN-26-setup-CI-CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies and test with Maven
        run: mvn clean install

  deploy:
    runs-on: test
    steps:
      - name: stop running application
        run: sudo systemctl stop talk_and_travel
      - name: fetch updated code
        run: cd /home/admin/talk-and-travel && sudo git pull
      - name: run service
        run: sudo systemctl start talk_and_travel